// microfrontend2/src/lib/Counter.svelte
<script lang="ts">
  let count: number = 0

  const onClick = () => {
    //console.log('svelte: counter onClick')
    count += 1
  }
</script>

<button class="p-2 flex space-x-2 items-center rounded-md bg-slate-700" on:click={onClick}>
  <img src="http://localhost:5002/svelte.svg" alt="Svelte Logo" style="width:1rem" />
  <span>Microfrontend2: Counter {count}</span>
</button>

// microfrontend1/src/components/Counter.tsx
// file: microfrontend1/src/components/Counter.tsx
import { useState } from 'react'

export default function Counter() {
  const [count, setCount] = useState(0)

  const onClick = () => {
    console.log('react: counter onClick')
    setCount((count) => count + 1)
  }

  return (
    <button className="p-2 flex space-x-2 items-center rounded-md bg-slate-700" onClick={onClick}>
      <img src="http://localhost:5001/react.svg" alt="React Logo" style={{width: '1.5rem'}}/>
      <span style={{marginLeft: '0.25rem'}}>Microfrontend1: Counter: {count}</span>
    </button>
  )
}
